// MSPager setup & update web app (FRD-021, FRD-024, FRD-025).
// Everything runs in the browser; the group password and key never leave it except to the pager.
// Protocol: docs/pager_config_protocol.md. Reference clients: bin/pager_setup.py, bin/pager_ota.py

import { WORDS } from "./words.js";

// ------------------------------------------------------------------ constants

const NUS = "6e400001-b5a3-f393-e0a9-e50e24dcca9e";
const NUS_RX = "6e400002-b5a3-f393-e0a9-e50e24dcca9e";   // write: app -> pager
const NUS_TX = "6e400003-b5a3-f393-e0a9-e50e24dcca9e";   // notify: pager -> app
const DFU = "00001530-1212-efde-1523-785feabcd123";      // Nordic legacy DFU (nRF52 bootloader)
const DFU_CONTROL = "00001531-1212-efde-1523-785feabcd123";
const DFU_PACKET = "00001532-1212-efde-1523-785feabcd123";

const CMD_CONFIG = 0x70, CMD_OTA = 0x71;
const RESP_OK = 0x00, RESP_ERR = 0x01;
const OTA_INFO = 0, OTA_BEGIN = 1, OTA_DATA = 2, OTA_END = 3, OTA_DFU = 0x10;
const CFG_BEGIN = 1, CFG_DATA = 2, CFG_COMMIT = 3, CFG_STATUS = 4, CFG_CLEAR = 5;
const CFG_CHUNK = 128;
const OTA_CHUNK = 160;   // frame 7 + 160 <= 173 (MTU 176 - 3)
const OTA_WINDOW = 4;    // frames per acknowledgement = the pager's receive queue
const DFU_PKT = 20, DFU_PRN = 10;

// password -> channel key (FRD-025). NEVER change these: all pagers of a group must derive the same key.
const KDF_SALT_PREFIX = "MSPager/v1/channel-key/";
const KDF_ITERATIONS = 600000;

const REGIONS = ["EU", "UK", "US", "CA", "AU", "NZ", "IN", "KR"];
const PRESET_REGIONS = ["EU", "UK", "US", "CA"];
const BUILTIN_QUESTIONS = ["Angekommen?", "Brauche Hilfe", "Standort?", "Mein Standort"];
const ERR_NAMES = { 1: "command not supported (not an MSPager firmware?)", 4: "bad state", 6: "illegal argument" };

const enc = new TextEncoder(), dec = new TextDecoder();
const bytesOf = (s) => enc.encode(s).length;
const $ = (id) => document.getElementById(id);
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

// ------------------------------------------------------------------ password + key

// 4 random words, uniform (rejection sampling on 16-bit values: 7776 * 8 = 62208 < 65536)
export function generatePassphrase(n = 4) {
  const out = [];
  const buf = new Uint16Array(1);
  while (out.length < n) {
    crypto.getRandomValues(buf);
    if (buf[0] < WORDS.length * 8) out.push(WORDS[buf[0] % WORDS.length]);
  }
  return out.join("-");
}

// case, spaces and separators don't matter: "Tulip Harbor-orbit_PASTE" == "tulip-harbor-orbit-paste"
export function normalizePassphrase(p) {
  return p.normalize("NFC").toLowerCase().split(/[\s\-_.,;:+\/]+/).filter(Boolean).join("-");
}

export function passphraseStrength(p) {
  const words = normalizePassphrase(p).split("-").filter(Boolean);
  const listed = words.length > 0 && words.every((w) => WORDS.includes(w));
  if (listed) return { bits: Math.round(words.length * Math.log2(WORDS.length)), words: words.length, listed };
  const chars = normalizePassphrase(p).length;
  return { bits: Math.round(chars * 2.5), words: words.length, listed };   // rough guess for own passwords
}

export async function deriveChannelKey(passphrase, channelName) {
  const pw = enc.encode(normalizePassphrase(passphrase));
  const salt = enc.encode(KDF_SALT_PREFIX + channelName);
  const base = await crypto.subtle.importKey("raw", pw, "PBKDF2", false, ["deriveBits"]);
  const bits = await crypto.subtle.deriveBits({ name: "PBKDF2", hash: "SHA-256", salt, iterations: KDF_ITERATIONS }, base, 128);
  return [...new Uint8Array(bits)].map((b) => b.toString(16).padStart(2, "0")).join("");
}

// ------------------------------------------------------------------ YAML (subset the pager parses)

const q = (s) => '"' + s.replace(/\\/g, "\\\\").replace(/"/g, '\\"') + '"';

export function buildYaml(setup) {
  const lines = ["# MSPager setup, generated by the web app", "version: 1"];
  if (setup.nickname) lines.push(`nickname: ${q(setup.nickname)}`);
  if (setup.region) lines.push("radio:", `  region: ${setup.region}`);
  if (setup.channel) lines.push("channel:", `  name: ${q(setup.channel)}`, `  key: ${setup.key}`);
  if (setup.questions.length) {
    lines.push("questions:");
    for (const qu of setup.questions) {
      lines.push(`  - text: ${q(qu.text)}`, `    replies: [${qu.replies.map(q).join(", ")}]`);
    }
  }
  return lines.join("\n") + "\n";
}

// same limits as the pager (PagerConfig.h); the pager checks again and reports the line
export function validateSetup(s) {
  const errors = [];
  if (s.nickname && (bytesOf(s.nickname) > 31 || /[:\[\]]/.test(s.nickname))) errors.push("Nickname: max 31 bytes, no : [ ]");
  if (!s.channel) errors.push("Channel name is missing");
  else if (bytesOf(s.channel) > 31 || s.channel.toLowerCase() === "public") errors.push("Channel name: max 31 bytes, not 'Public'");
  if (!/^[0-9a-f]{32}$/.test(s.key || "")) errors.push("Channel key missing: enter a password or a 32-character hex key");
  if (s.questions.length > 12) errors.push("At most 12 questions");
  const seen = new Set();
  s.questions.forEach((qu, i) => {
    const n = `Question ${i + 1}`;
    if (!qu.text) errors.push(`${n}: text is empty`);
    if (bytesOf(qu.text) > 40) errors.push(`${n}: longer than 40 bytes`);
    if (seen.has(qu.text)) errors.push(`${n}: duplicate text`);
    seen.add(qu.text);
    if (qu.replies.length < 1 || qu.replies.length > 6) errors.push(`${n}: 1 to 6 replies`);
    qu.replies.forEach((r) => { if (bytesOf(r) > 40) errors.push(`${n}: reply "${r}" longer than 40 bytes`); });
  });
  return errors;
}

// ------------------------------------------------------------------ MD5 (WebCrypto has none; the ESP32 update checks it)

export function md5(data) {
  const K = new Uint32Array(64), S = [7, 12, 17, 22, 5, 9, 14, 20, 4, 11, 16, 23, 6, 10, 15, 21];
  for (let i = 0; i < 64; i++) K[i] = Math.floor(Math.abs(Math.sin(i + 1)) * 2 ** 32) >>> 0;
  const len = data.length, total = ((len + 8) >> 6) + 1;
  const buf = new Uint8Array(total * 64);
  buf.set(data);
  buf[len] = 0x80;
  const dv = new DataView(buf.buffer);
  dv.setUint32(total * 64 - 8, (len * 8) >>> 0, true);
  dv.setUint32(total * 64 - 4, Math.floor(len / 2 ** 29), true);
  let a0 = 0x67452301, b0 = 0xefcdab89, c0 = 0x98badcfe, d0 = 0x10325476;
  const M = new Uint32Array(16);
  for (let blk = 0; blk < total; blk++) {
    for (let i = 0; i < 16; i++) M[i] = dv.getUint32(blk * 64 + i * 4, true);
    let A = a0, B = b0, C = c0, D = d0;
    for (let i = 0; i < 64; i++) {
      let F, g;
      if (i < 16) { F = (B & C) | (~B & D); g = i; }
      else if (i < 32) { F = (D & B) | (~D & C); g = (5 * i + 1) % 16; }
      else if (i < 48) { F = B ^ C ^ D; g = (3 * i + 5) % 16; }
      else { F = C ^ (B | ~D); g = (7 * i) % 16; }
      F = (F + A + K[i] + M[g]) >>> 0;
      A = D; D = C; C = B;
      const s = S[(i >> 4) * 4 + (i & 3)];
      B = (B + ((F << s) | (F >>> (32 - s)))) >>> 0;
    }
    a0 = (a0 + A) >>> 0; b0 = (b0 + B) >>> 0; c0 = (c0 + C) >>> 0; d0 = (d0 + D) >>> 0;
  }
  const out = new Uint8Array(16), ov = new DataView(out.buffer);
  [a0, b0, c0, d0].forEach((v, i) => ov.setUint32(i * 4, v, true));
  return out;
}

// ------------------------------------------------------------------ zip (DFU package: manifest.json, firmware.bin, firmware.dat)

export async function readZip(bytes) {
  const dv = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  let eocd = -1;
  for (let i = bytes.length - 22; i >= Math.max(0, bytes.length - 65557); i--) {
    if (dv.getUint32(i, true) === 0x06054b50) { eocd = i; break; }
  }
  if (eocd < 0) throw new Error("not a zip file");
  const count = dv.getUint16(eocd + 10, true);
  let p = dv.getUint32(eocd + 16, true);
  const files = {};
  for (let k = 0; k < count; k++) {
    if (dv.getUint32(p, true) !== 0x02014b50) throw new Error("bad zip directory");
    const method = dv.getUint16(p + 10, true), csize = dv.getUint32(p + 20, true);
    const nlen = dv.getUint16(p + 28, true), xlen = dv.getUint16(p + 30, true), clen = dv.getUint16(p + 32, true);
    const local = dv.getUint32(p + 42, true);
    const name = dec.decode(bytes.subarray(p + 46, p + 46 + nlen));
    const start = local + 30 + dv.getUint16(local + 26, true) + dv.getUint16(local + 28, true);
    const raw = bytes.subarray(start, start + csize);
    if (method === 0) files[name] = raw.slice();
    else if (method === 8) {
      const stream = new Blob([raw]).stream().pipeThrough(new DecompressionStream("deflate-raw"));
      files[name] = new Uint8Array(await new Response(stream).arrayBuffer());
    } else throw new Error(`unsupported zip compression ${method}`);
    p += 46 + nlen + xlen + clen;
  }
  return files;
}

// "MSPAGER-BOARD:<env>\0" in every pager image (PagerOta.h)
export function boardOf(image) {
  const marker = enc.encode("MSPAGER-BOARD:");
  outer: for (let i = 0; i + marker.length < image.length; i++) {
    for (let j = 0; j < marker.length; j++) if (image[i + j] !== marker[j]) continue outer;
    let end = i + marker.length;
    while (end < image.length && image[end] !== 0 && end - i < 80) end++;
    return dec.decode(image.subarray(i + marker.length, end));
  }
  return null;
}

const isEsp32App = (b) => b.length > 64 && b[0] === 0xe9 && new DataView(b.buffer, b.byteOffset).getUint32(32, true) === 0xabcd5432;

// ------------------------------------------------------------------ BLE link to the pager (MeshCore companion protocol)

class PagerLink {
  constructor() { this.queue = []; this.waiters = []; this.device = null; }

  async connect() {
    this.device = await navigator.bluetooth.requestDevice({
      filters: [{ namePrefix: "MeshCore-" }, { services: [NUS] }],
      optionalServices: [NUS],
    });
    this.device.addEventListener("gattserverdisconnected", () => this.onDisconnect && this.onDisconnect());
    const server = await this.device.gatt.connect();
    const svc = await server.getPrimaryService(NUS);
    this.rx = await svc.getCharacteristic(NUS_RX);
    this.tx = await svc.getCharacteristic(NUS_TX);
    this.tx.addEventListener("characteristicvaluechanged", (e) => {
      const v = e.target.value;
      this.push(new Uint8Array(v.buffer, v.byteOffset, v.byteLength).slice());
    });
    await this.tx.startNotifications();   // the OS asks for the PIN here (first time)
    return this.device.name;
  }

  get connected() { return this.device && this.device.gatt.connected; }
  disconnect() { if (this.connected) this.device.gatt.disconnect(); }

  push(frame) {
    if (!(frame[0] === RESP_OK || frame[0] === RESP_ERR || frame[0] === CMD_CONFIG || frame[0] === CMD_OTA)) return;   // 0x80+: pushes
    const w = this.waiters.shift();
    if (w) w(frame); else this.queue.push(frame);
  }

  reply(timeout = 15000) {
    if (this.queue.length) return Promise.resolve(this.queue.shift());
    return new Promise((resolve, reject) => {
      const t = setTimeout(() => { this.waiters = this.waiters.filter((x) => x !== done); reject(new Error("no answer from the pager")); }, timeout);
      const done = (f) => { clearTimeout(t); resolve(f); };
      this.waiters.push(done);
    });
  }

  async send(bytes) { await this.rx.writeValueWithResponse(bytes); }

  async request(bytes, timeout) { await this.send(bytes); return this.reply(timeout); }

  // 0x70 / 0x71 result frames: code, status, line u16, UTF-8 message
  static result(f) {
    if (f[0] === RESP_ERR) throw new Error(ERR_NAMES[f[1]] || `error ${f[1]}`);
    if (f[0] === RESP_OK) return { status: 0, line: 0, msg: "" };
    return { status: f[1], line: f[2] | (f[3] << 8), msg: dec.decode(f.subarray(4)) };
  }

  async info() {
    const r = PagerLink.result(await this.request(new Uint8Array([CMD_OTA, OTA_INFO])));
    return Object.fromEntries(r.msg.split(" ").filter((kv) => kv.includes("=")).map((kv) => kv.split("=")));
  }

  async configCmd(op) { return PagerLink.result(await this.request(new Uint8Array([CMD_CONFIG, op]))); }

  async uploadYaml(yaml) {
    const data = enc.encode(yaml);
    if (data.length > 4096) throw new Error("setup larger than 4096 bytes");
    const expectOk = async (frame) => {
      const f = await this.request(frame);
      if (f[0] === RESP_OK) return;
      throw new Error(PagerLink.result(f).msg || "unexpected answer");   // result() throws for ERR frames
    };
    await expectOk(new Uint8Array([CMD_CONFIG, CFG_BEGIN, data.length & 0xff, data.length >> 8]));
    for (let off = 0; off < data.length; off += CFG_CHUNK) {
      const chunk = data.subarray(off, off + CFG_CHUNK);
      const f = new Uint8Array(4 + chunk.length);
      f.set([CMD_CONFIG, CFG_DATA, off & 0xff, off >> 8]);
      f.set(chunk, 4);
      await expectOk(f);
    }
    return this.configCmd(CFG_COMMIT);
  }

  // ESP32: stream the app image, acknowledgement every OTA_WINDOW frames
  async updateEsp32(image, progress) {
    const begin = new Uint8Array(2 + 4 + 16);
    begin.set([CMD_OTA, OTA_BEGIN]);
    new DataView(begin.buffer).setUint32(2, image.length, true);
    begin.set(md5(image), 6);
    let r = PagerLink.result(await this.request(begin));
    if (r.status) throw new Error(r.msg);
    const n = Math.ceil(image.length / OTA_CHUNK);
    const t0 = performance.now();
    for (let k = 0; k < n; k++) {
      const off = k * OTA_CHUNK, chunk = image.subarray(off, off + OTA_CHUNK);
      const ack = k % OTA_WINDOW === OTA_WINDOW - 1 || k === n - 1;
      const f = new Uint8Array(7 + chunk.length);
      f.set([CMD_OTA, OTA_DATA]);
      new DataView(f.buffer).setUint32(2, off, true);
      f[6] = ack ? 1 : 0;
      f.set(chunk, 7);
      await this.send(f);
      if (ack) {
        const a = await this.reply();
        if (a[0] !== RESP_OK) throw new Error(PagerLink.result(a).msg || "update failed");
        progress(off + chunk.length, image.length, (off + chunk.length) / ((performance.now() - t0) / 1000));
      }
    }
    r = PagerLink.result(await this.request(new Uint8Array([CMD_OTA, OTA_END]), 30000));
    if (r.status) throw new Error(r.msg);
    return r.msg;
  }

  async enterDfu() {
    const r = PagerLink.result(await this.request(new Uint8Array([CMD_OTA, OTA_DFU])));
    if (r.status) throw new Error(r.msg);
  }
}

// ------------------------------------------------------------------ Nordic legacy DFU (T114 bootloader)

async function legacyDfu(image, init, progress, log) {
  const device = await navigator.bluetooth.requestDevice({
    filters: [{ services: [DFU] }, { namePrefix: "AdaDFU" }, { namePrefix: "T114" }],
    optionalServices: [DFU],
  });
  log(`Bootloader: ${device.name || "?"}`);
  const server = await device.gatt.connect();
  const svc = await server.getPrimaryService(DFU);
  const ctrl = await svc.getCharacteristic(DFU_CONTROL);
  const pkt = await svc.getCharacteristic(DFU_PACKET);
  const notes = [], waiters = [];
  ctrl.addEventListener("characteristicvaluechanged", (e) => {
    const v = e.target.value, f = new Uint8Array(v.buffer, v.byteOffset, v.byteLength).slice();
    const w = waiters.shift();
    if (w) w(f); else notes.push(f);
  });
  await ctrl.startNotifications();
  const note = (timeout = 60000) => notes.length ? Promise.resolve(notes.shift()) : new Promise((res, rej) => {
    const t = setTimeout(() => rej(new Error("DFU: no answer")), timeout);
    waiters.push((f) => { clearTimeout(t); res(f); });
  });
  const expect = async (op) => {
    for (;;) {
      const f = await note();
      if (f[0] === 0x10 && f[1] === op) { if (f[2] !== 1) throw new Error(`DFU step ${op} failed (status ${f[2]})`); return; }
    }
  };
  const control = (bytes) => ctrl.writeValueWithResponse(new Uint8Array(bytes));
  const packet = (bytes) => pkt.writeValueWithoutResponse(bytes);

  try {
    await control([0x01, 0x04]);                                   // START_DFU, application
    const sizes = new Uint8Array(12);
    new DataView(sizes.buffer).setUint32(8, image.length, true);   // softdevice 0, bootloader 0, app
    await packet(sizes);
    await expect(0x01);
    await control([0x02, 0x00]);                                   // init packet
    await packet(init);
    await control([0x02, 0x01]);
    await expect(0x02);
    await control([0x08, DFU_PRN, 0]);                             // receipt every DFU_PRN packets
    await control([0x03]);                                         // RECEIVE_FIRMWARE_IMAGE
    const t0 = performance.now();
    const n = Math.ceil(image.length / DFU_PKT);
    for (let k = 0; k < n; k++) {
      await packet(image.subarray(k * DFU_PKT, (k + 1) * DFU_PKT));
      if (k % DFU_PRN === DFU_PRN - 1) {
        let f;
        do { f = await note(30000); if (f[0] === 0x10) throw new Error("DFU aborted by the bootloader"); } while (f[0] !== 0x11);
        const done = new DataView(f.buffer).getUint32(1, true);
        progress(done, image.length, done / ((performance.now() - t0) / 1000));
      }
    }
    await expect(0x03);
    progress(image.length, image.length, 0);
    await control([0x04]);                                         // VALIDATE
    await expect(0x04);
    try { await control([0x05]); } catch (e) { /* resets right away */ }   // ACTIVATE_AND_RESET
  } finally {
    if (device.gatt.connected) device.gatt.disconnect();
  }
}

// ------------------------------------------------------------------ UI

const link = new PagerLink();
let pagerInfo = null;

function log(msg, kind = "") {
  const li = document.createElement("li");
  li.textContent = msg;
  if (kind) li.className = kind;
  $("log").prepend(li);
}

function setBusy(busy) {
  document.querySelectorAll("button[data-needs-pager]").forEach((b) => (b.disabled = busy || !link.connected));
}

function showPager() {
  const ok = link.connected;
  $("pager-state").textContent = ok
    ? `${link.device.name} · ${pagerInfo ? `${pagerInfo.board} · ${pagerInfo.fw}` : ""}`
    : "not connected";
  $("pager-state").classList.toggle("on", ok);
  $("connect").textContent = ok ? "Disconnect" : "Connect pager";
  setBusy(false);
}

async function run(label, fn) {
  setBusy(true);
  try { await fn(); }
  catch (e) { log(`${label}: ${e.message}`, "err"); }
  finally { setBusy(false); }
}

// ---- group + pager form, kept in localStorage (never the password or key)

const STORE = "mspager-setup-v1";
function saveForm() {
  const data = { channel: $("channel").value, region: $("region").value, nickname: $("nickname").value, questions: readQuestions() };
  try { localStorage.setItem(STORE, JSON.stringify(data)); } catch (e) { /* private mode */ }
}
function loadForm() {
  let data = null;
  try { data = JSON.parse(localStorage.getItem(STORE)); } catch (e) { /* empty */ }
  data = data || { channel: "Familie", region: "EU", nickname: "", questions: [] };
  $("channel").value = data.channel || "";
  $("region").value = data.region || "EU";
  $("nickname").value = data.nickname || "";
  $("questions").innerHTML = "";
  (data.questions || []).forEach(addQuestion);
}

function addQuestion(qu = { text: "", replies: [] }) {
  const tpl = $("question-tpl").content.firstElementChild.cloneNode(true);
  tpl.querySelector(".q-text").value = qu.text;
  tpl.querySelector(".q-replies").value = qu.replies.join("\n");
  tpl.querySelector(".q-remove").onclick = () => { tpl.remove(); refresh(); };
  tpl.addEventListener("input", refresh);
  $("questions").append(tpl);
  refresh();
}

function readQuestions() {
  return [...$("questions").children].map((el) => ({
    text: el.querySelector(".q-text").value.trim(),
    replies: el.querySelector(".q-replies").value.split("\n").map((s) => s.trim()).filter(Boolean),
  }));
}

let derived = { input: null, key: "" };
let deriveTimer = null;

function currentKey() {
  return $("key-mode").value === "hex" ? $("hexkey").value.trim().toLowerCase() : derived.key;
}

function currentSetup() {
  return { nickname: $("nickname").value.trim(), channel: $("channel").value.trim(), key: currentKey(), region: $("region").value, questions: readQuestions() };
}

function refresh() {
  const s = currentSetup();
  $("yaml").textContent = buildYaml({ ...s, key: s.key || "<derived from the password>" });
  const errs = validateSetup(s);
  $("errors").innerHTML = "";
  errs.forEach((e) => { const li = document.createElement("li"); li.textContent = e; $("errors").append(li); });
  $("upload").dataset.invalid = errs.length ? "1" : "";
  $("q-count").textContent = `${s.questions.length}/12`;
  document.querySelectorAll(".q-builtin").forEach((el) => el.remove());
  [...$("questions").children].forEach((el) => {
    if (BUILTIN_QUESTIONS.includes(el.querySelector(".q-text").value.trim())) {
      const note = document.createElement("small");
      note.className = "q-builtin";
      note.textContent = "Built-in question: only its replies are replaced.";
      el.querySelector(".q-text").after(note);
    }
  });
  saveForm();
}

function updatePasswordInfo() {
  const p = $("password").value;
  const st = passphraseStrength(p);
  const el = $("strength");
  if (!p) { el.textContent = ""; el.className = ""; }
  else if (st.listed && st.words >= 4) { el.textContent = `Strong: ${st.words} list words ≈ ${st.bits} bits`; el.className = "good"; }
  else if (st.bits >= 60) { el.textContent = `Probably OK (≈ ${st.bits} bits). A generated 4-word password is safer.`; el.className = "warn"; }
  else { el.textContent = "Too weak: use at least 4 random words (Generate)."; el.className = "bad"; }
  // derive after typing stops (PBKDF2 takes ~0.5 s)
  clearTimeout(deriveTimer);
  const input = `${normalizePassphrase(p)}\u0000${$("channel").value.trim()}`;
  if (!p || (!st.listed || st.words < 4) && st.bits < 60) { derived = { input, key: "" }; showKey(); refresh(); return; }
  if (input === derived.input) return;
  $("derived").textContent = "deriving …";
  deriveTimer = setTimeout(async () => {
    const key = await deriveChannelKey(p, $("channel").value.trim());
    derived = { input, key };
    showKey();
    refresh();
  }, 400);
}

function showKey() {
  $("derived").textContent = derived.key || "—";
}

function progressBar(done, total, rate) {
  $("progress").hidden = false;
  $("progress").value = done / total;
  $("progress-text").textContent = `${Math.floor((done * 100) / total)} % · ${(done / 1024).toFixed(0)} / ${(total / 1024).toFixed(0)} KB` + (rate ? ` · ${(rate / 1024).toFixed(1)} KB/s` : "");
}

async function doUpdate() {
  const file = $("fw-file").files[0];
  if (!file) throw new Error("choose a firmware file first");
  if (!pagerInfo) pagerInfo = await link.info();
  const data = new Uint8Array(await file.arrayBuffer());
  if (pagerInfo.ota === "esp32") {
    if (!isEsp32App(data)) throw new Error("not an ESP32 app image: use the .bin without -merged");
    const board = boardOf(data);
    if (board !== pagerInfo.board) throw new Error(`the file is for ${board || "an unknown board"}, this pager is ${pagerInfo.board}`);
    log(`Updating ${pagerInfo.board} (${(data.length / 1024).toFixed(0)} KB) …`);
    const msg = await link.updateEsp32(data, progressBar);
    log(`Update done: ${msg}. The pager restarts; reconnect in a few seconds.`, "ok");
  } else if (pagerInfo.ota === "nrf-dfu") {
    let files;
    try { files = await readZip(data); } catch (e) { throw new Error("not a DFU package: use the .zip"); }
    const image = files["firmware.bin"], init = files["firmware.dat"];
    if (!image || !init) throw new Error("DFU package without firmware.bin / firmware.dat");
    const board = boardOf(image);
    if (board !== pagerInfo.board) throw new Error(`the file is for ${board || "an unknown board"}, this pager is ${pagerInfo.board}`);
    await link.enterDfu();
    log("The pager restarts into update mode. Press “Select bootloader” and choose the new device.");
    link.disconnect();
    $("dfu-step").hidden = false;
    $("dfu-go").onclick = () => run("Update", async () => {
      $("dfu-step").hidden = true;
      await legacyDfu(image, init, progressBar, log);
      log("Update done. The pager restarts with the new firmware.", "ok");
    });
  } else {
    throw new Error("this pager can't be updated over Bluetooth");
  }
}

function init() {
  if (!navigator.bluetooth) {
    $("no-ble").hidden = false;
    document.querySelectorAll("button[data-needs-ble]").forEach((b) => (b.disabled = true));
  }
  $("region").innerHTML = REGIONS.map((r) => `<option>${r}</option>`).join("");
  loadForm();

  $("connect").onclick = () => run("Connect", async () => {
    if (link.connected) { link.disconnect(); return; }
    const name = await link.connect();
    log(`Connected to ${name}`);
    try { pagerInfo = await link.info(); log(`${pagerInfo.board} · firmware ${pagerInfo.fw}`); }
    catch (e) { pagerInfo = null; log("No update support in this firmware (flash once over USB)", "warn"); }
    const st = await link.configCmd(CFG_STATUS);
    log(`Active setup: ${st.msg}`);
    const nick = /nickname=(\S+)/.exec(st.msg);
    if (nick && !$("nickname").value) { $("nickname").value = nick[1]; refresh(); }
    showPager();
  });
  link.onDisconnect = () => { pagerInfo = null; showPager(); };

  $("generate").onclick = () => { $("password").value = generatePassphrase(); $("password").type = "text"; updatePasswordInfo(); };
  $("show-pw").onchange = (e) => ($("password").type = e.target.checked ? "text" : "password");
  $("password").oninput = updatePasswordInfo;
  $("channel").oninput = () => { updatePasswordInfo(); refresh(); };
  $("key-mode").onchange = () => {
    const hex = $("key-mode").value === "hex";
    $("pw-block").hidden = hex;
    $("hex-block").hidden = !hex;
    refresh();
  };
  $("hexkey").oninput = refresh;
  $("hexgen").onclick = () => {
    $("hexkey").value = [...crypto.getRandomValues(new Uint8Array(16))].map((b) => b.toString(16).padStart(2, "0")).join("");
    refresh();
  };
  ["nickname", "region"].forEach((id) => ($(id).oninput = refresh));
  $("add-question").onclick = () => addQuestion();

  $("upload").onclick = () => run("Upload", async () => {
    const s = currentSetup();
    const errs = validateSetup(s);
    if (errs.length) throw new Error(errs[0]);
    const r = await link.uploadYaml(buildYaml(s));
    if (r.status === 0) log(`Setup stored: ${r.msg}`, "ok");
    else log(r.line ? `Rejected, line ${r.line}: ${r.msg}` : `Failed: ${r.msg}`, "err");
  });
  $("status").onclick = () => run("Status", async () => log(`Active setup: ${(await link.configCmd(CFG_STATUS)).msg}`));
  $("clear").onclick = () => run("Reset", async () => {
    if (!confirm("Remove the uploaded setup? The pager goes back to its build configuration.")) return;
    log(`Setup removed: ${(await link.configCmd(CFG_CLEAR)).msg}`, "ok");
  });
  $("download").onclick = () => {
    const s = currentSetup();
    const blob = new Blob([buildYaml(s)], { type: "text/yaml" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = `pager-${s.nickname || "setup"}.yaml`;
    a.click();
    URL.revokeObjectURL(a.href);
  };
  $("update").onclick = () => run("Update", doUpdate);

  showPager();
  refresh();
}

if (typeof document !== "undefined") init();
